using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;

namespace WindWakerItemizer
{
    internal record Items(int Id, string Name)
    {
        public static Items HeartPickup           { get; } = new(0, "Heart (Pickup)");
        public static Items GreenRupee            { get; } = new(1, "Green Rupee (1)");
        public static Items BlueRupee             { get; } = new(2, "Blue Rupee (5)");
        public static Items YellowRupee           { get; } = new(3, "Yellow Rupee (10)");
        public static Items RedRupee              { get; } = new(4, "Red Rupee (20)");
        public static Items PurpleRupee           { get; } = new(5, "Purple Rupee (50)");
        public static Items OrangeRupee           { get; } = new(6, "Orange Rupee (100)");
        public static Items HeartPiece            { get; } = new(7, "Piece of Heart");
        public static Items HeartContainer        { get; } = new(8, "Heart Container");
        public static Items MagicJarSmall         { get; } = new(9, "Small Magic Jar");
        public static Items MagicJarLarge         { get; } = new(10, "Large Magic Jar");
        public static Items Bombs5                { get; } = new(11, "5 Bombs");
        public static Items Bombs10               { get; } = new(12, "10 Bombs");
        public static Items Bombs20               { get; } = new(13, "20 Bombs");
        public static Items Bombs30               { get; } = new(14, "30 Bombs");
        public static Items SilverRupee           { get; } = new(15, "Silver Rupee (200)");
        public static Items Arrows10              { get; } = new(16, "10 Arrows");
        public static Items Arrows20              { get; } = new(17, "20 Arrows");
        public static Items Arrows30              { get; } = new(18, "30 Arrows");
        public static Items Empty19               { get; } = new(19, "[Slot 19]");
        public static Items Empty20               { get; } = new(20, "[Slot 20]");
        public static Items SmallKey              { get; } = new(21, "Small Key");
        public static Items FairyPickup           { get; } = new(22, "Fairy (Pickup)");
        public static Items Empty23               { get; } = new(23, "[Slot 23]");
        public static Items Empty24               { get; } = new(24, "[Slot 24]");
        public static Items Empty25               { get; } = new(25, "[Slot 25]");
        public static Items YellowRupeeJoke       { get; } = new(26, "Yellow Rupee (Joke Message)");
        public static Items Empty27               { get; } = new(27, "[Slot 27]");
        public static Items Empty28               { get; } = new(28, "[Slot 28]");
        public static Items Empty29               { get; } = new(29, "[Slot 29]");
        public static Items ThreeHeartsPickup     { get; } = new(30, "3 Hearts (Pickup)");
        public static Items JoyPendant            { get; } = new(31, "Joy Pendant");
        public static Items Telescope             { get; } = new(32, "Telescope");
        public static Items TingleTuner           { get; } = new(33, "Tingle Tuner");
        public static Items WindWaker             { get; } = new(34, "Wind Waker");
        public static Items PictoBox              { get; } = new(35, "Picto Box");
        public static Items SpoilsBag             { get; } = new(36, "Spoils Bag");
        public static Items GrapplingHook         { get; } = new(37, "Grappling Hook");
        public static Items DeluxePictoBox        { get; } = new(38, "Deluxe Picto Box");
        public static Items HerosBow              { get; } = new(39, "Hero's Bow");
        public static Items PowerBracelets        { get; } = new(40, "Power Bracelets");
        public static Items IronBoots             { get; } = new(41, "Iron Boots");
        public static Items MagicArmor            { get; } = new(42, "Magic Armor");
        public static Items Empty43               { get; } = new(43, "[Slot 43]");
        public static Items BaitBag               { get; } = new(44, "Bait Bag");
        public static Items Boomerang             { get; } = new(45, "Boomerang");
        public static Items Empty46               { get; } = new(46, "[Slot 46]");
        public static Items Hookshot              { get; } = new(47, "Hookshot");
        public static Items DeliveryBag           { get; } = new(48, "Delivery Bag");
        public static Items Bombs                 { get; } = new(49, "Bombs");
        public static Items HerosClothes          { get; } = new(50, "Hero's Clothes");
        public static Items SkullHammer           { get; } = new(51, "Skull Hammer");
        public static Items DekuLeaf              { get; } = new(52, "Deku Leaf");
        public static Items FireIceArrows         { get; } = new(53, "Fire and Ice Arrows");
        public static Items LightArrow            { get; } = new(54, "Light Arrow");
        public static Items HerosNewClothes       { get; } = new(55, "Hero's New Clothes");
        public static Items HerosSword            { get; } = new(56, "Hero's Sword");
        public static Items MasterSwordPowerless  { get; } = new(57, "Master Sword (Powerless)");
        public static Items MasterSwordHalfPower  { get; } = new(58, "Master Sword (Half-Power)");
        public static Items HerosShield           { get; } = new(59, "Hero's Shield");
        public static Items MirrorShield          { get; } = new(60, "Mirror Shield");
        public static Items RecoveredHerosSword   { get; } = new(61, "Hero's Sword (Recovered)");
        public static Items MasterSwordFullPower  { get; } = new(62, "Master Sword (Full Power)");
        public static Items HeartPieceAltMsg      { get; } = new(63, "Piece of Heart (Alt. Message)");
        public static Items Empty64               { get; } = new(64, "[Slot 64]");
        public static Items Empty65               { get; } = new(65, "[Slot 65]");
        public static Items PiratesCharm          { get; } = new(66, "Pirate's Charm");
        public static Items HerosCharm            { get; } = new(67, "Hero's Charm");
        public static Items Empty68               { get; } = new(68, "[Slot 68]");
        public static Items SkullNecklace         { get; } = new(69, "Skull Necklace");
        public static Items BokoBabaSeed          { get; } = new(70, "Boko Baba Seed");
        public static Items GoldenFeather         { get; } = new(71, "Golden Feather");
        public static Items KnightsCrest          { get; } = new(72, "Knights' Crest");
        public static Items RedChuJelly           { get; } = new(73, "Red Chu Jelly");
        public static Items GreenChuJelly         { get; } = new(74, "Green Chu Jelly");
        public static Items BlueChuJelly          { get; } = new(75, "Blue Chu Jelly");
        public static Items DungeonMap            { get; } = new(76, "Dungeon Map");
        public static Items Compass               { get; } = new(77, "Compass");
        public static Items BigKey                { get; } = new(78, "Big Key");
        public static Items Empty79               { get; } = new(79, "[Slot 79]");
        public static Items EmptyBottle           { get; } = new(80, "Empty Bottle");
        public static Items RedPotion             { get; } = new(81, "Red Potion");
        public static Items GreenPotion           { get; } = new(82, "Green Potion");
        public static Items BluePotion            { get; } = new(83, "Blue Potion");
        public static Items ElixirSoupHalf        { get; } = new(84, "Elixir Soup (1/2)");
        public static Items ElixirSoupFull        { get; } = new(85, "Elixir Soup");
        public static Items BottledWater          { get; } = new(86, "Bottled Water");
        public static Items BottledFairy          { get; } = new(87, "Fairy in a Bottle");
        public static Items ForestFirefly         { get; } = new(88, "Forest Firefly");
        public static Items ForestWater           { get; } = new(89, "Forest Water");
        public static Items Empty90               { get; } = new(90, "[Slot 90]");
        public static Items Empty91               { get; } = new(91, "[Slot 91]");
        public static Items Empty92               { get; } = new(92, "[Slot 92]");
        public static Items Empty93               { get; } = new(93, "[Slot 93]");
        public static Items Empty94               { get; } = new(94, "[Slot 94]");
        public static Items Empty95               { get; } = new(95, "[Slot 95]");
        public static Items Empty96               { get; } = new(96, "[Slot 96]");
        public static Items TriforceShard1        { get; } = new(97, "Triforce Shard 1");
        public static Items TriforceShard2        { get; } = new(98, "Triforce Shard 2");
        public static Items TriforceShard3        { get; } = new(99, "Triforce Shard 3");
        public static Items TriforceShard4        { get; } = new(100, "Triforce Shard 4");
        public static Items TriforceShard5        { get; } = new(101, "Triforce Shard 5");
        public static Items TriforceShard6        { get; } = new(102, "Triforce Shard 6");
        public static Items TriforceShard7        { get; } = new(103, "Triforce Shard 7");
        public static Items TriforceShard8        { get; } = new(104, "Triforce Shard 8");
        public static Items NayrusPearl           { get; } = new(105, "Nayru's Pearl");
        public static Items DinsPearl             { get; } = new(106, "Din's Pearl");
        public static Items FaroresPearl          { get; } = new(107, "Farore's Pearl");
        public static Items Empty108              { get; } = new(108, "[Slot 108]]");
        public static Items WindsRequiem          { get; } = new(109, "Wind's Requiem");
        public static Items BalladOfGales         { get; } = new(110, "Ballad of Gales");
        public static Items CommandMelody         { get; } = new(111, "Command Melody");
        public static Items EarthGodsLyric        { get; } = new(112, "Earth God's Lyric");
        public static Items WindGodsAria          { get; } = new(113, "Wind God's Aria");
        public static Items SongOfPassing         { get; } = new(114, "Song of Passing");
        public static Items Empty115              { get; } = new(115, "[Slot 115]");
        public static Items Empty116              { get; } = new(116, "[Slot 116]");
        public static Items Empty117              { get; } = new(117, "[Slot 117]");
        public static Items Empty118              { get; } = new(118, "[Slot 118]");
        public static Items Empty119              { get; } = new(119, "[Slot 119]");
        public static Items Sail                  { get; } = new(120, "Sail");
        public static Items DecTriforceChart1     { get; } = new(121, "Triforce Chart 1 (Deciphered)");
        public static Items DecTriforceChart2     { get; } = new(122, "Triforce Chart 2 (Deciphered)");
        public static Items DecTriforceChart3     { get; } = new(123, "Triforce Chart 3 (Deciphered)");
        public static Items DecTriforceChart4     { get; } = new(124, "Triforce Chart 4 (Deciphered)");
        public static Items DecTriforceChart5     { get; } = new(125, "Triforce Chart 5 (Deciphered)");
        public static Items DecTriforceChart6     { get; } = new(126, "Triforce Chart 6 (Deciphered)");
        public static Items DecTriforceChart7     { get; } = new(127, "Triforce Chart 7 (Deciphered)");
        public static Items DecTriforceChart8     { get; } = new(128, "Triforce Chart 8 (Deciphered)");
        public static Items Empty129              { get; } = new(129, "[Slot 129]");
        public static Items AllPurposeBait        { get; } = new(130, "All-Purpose Bait");
        public static Items HyoiPear              { get; } = new(131, "Hyoi Pear");
        public static Items Empty132              { get; } = new(132, "[Slot 132]");
        public static Items Empty133              { get; } = new(133, "[Slot 133]");
        public static Items Empty134              { get; } = new(134, "[Slot 134]");
        public static Items Empty135              { get; } = new(135, "[Slot 135]");
        public static Items Empty136              { get; } = new(136, "[Slot 136]");
        public static Items Empty137              { get; } = new(137, "[Slot 137]");
        public static Items Empty138              { get; } = new(138, "[Slot 138]");
        public static Items Empty139              { get; } = new(139, "[Slot 139]");
        public static Items TownFlower            { get; } = new(140, "Town Flower");
        public static Items SeaFlower             { get; } = new(141, "Sea Flower");
        public static Items ExoticFlower          { get; } = new(142, "Exotic Flower");
        public static Items HerosFlag             { get; } = new(143, "Hero's Flag");
        public static Items BigCatchFlag          { get; } = new(144, "Big Catch Flag");
        public static Items BigSaleFlag           { get; } = new(145, "Big Sale Flag");
        public static Items Pinwheel              { get; } = new(146, "Pinwheel");
        public static Items SickleMoonFlag        { get; } = new(147, "Sickle Moon Flag");
        public static Items SkullTowerIdol        { get; } = new(148, "Skull Tower Idol");
        public static Items FountainIdol          { get; } = new(149, "Fountain Idol");
        public static Items PostmanStatue         { get; } = new(150, "Postman Statue");
        public static Items ShopGuruStatue        { get; } = new(151, "Shop Guru Statue");
        public static Items FathersLetter         { get; } = new(152, "Father's Letter");
        public static Items NoteToMom             { get; } = new(153, "Note to Mom");
        public static Items MaggiesLetter         { get; } = new(154, "Maggie's Letter");
        public static Items MoblinsLetter         { get; } = new(155, "Moblin's Letter");
        public static Items CabanaDeed            { get; } = new(156, "Cabana Deed");
        public static Items ComplimentaryId       { get; } = new(157, "Complimentary ID");
        public static Items FillUpCoupon          { get; } = new(158, "Fill-Up Coupon");
        public static Items LegendaryPictograph   { get; } = new(159, "Legendary Pictograph");
        public static Items Empty160              { get; } = new(160, "[Slot 160]");
        public static Items Empty161              { get; } = new(161, "[Slot 161]");
        public static Items Empty162              { get; } = new(162, "[Slot 162]");
        public static Items DragonTingleStatue    { get; } = new(163, "Dragon Tingle Statue");
        public static Items ForbiddenTingleStatue { get; } = new(164, "Forbidden Tingle Statue");
        public static Items GoddessTingleStatue   { get; } = new(165, "Goddess Tingle Statue");
        public static Items EarthTingleStatue     { get; } = new(166, "Earth Tingle Statue");
        public static Items WindTingleState       { get; } = new(167, "Wind Tingle Statue");
        public static Items Empty168              { get; } = new(168, "[Slot 168]");
        public static Items Empty169              { get; } = new(169, "[Slot 169]");
        public static Items HurricaneSpin         { get; } = new(170, "Hurricane Spin");
        public static Items Wallet1000            { get; } = new(171, "1000-Rupee Wallet");
        public static Items Wallet5000            { get; } = new(172, "5000-Rupee Wallet");
        public static Items BombBag60             { get; } = new(173, "60-Bomb Bag");
        public static Items BombBag99             { get; } = new(174, "99-Bomb Bag");
        public static Items Quiver60              { get; } = new(175, "60-Arrow Quiver");
        public static Items Quiver99              { get; } = new(176, "99-Arrow Quiver");
        public static Items MagicMeter            { get; } = new(177, "Magic Meter");
        public static Items MagicMeterUpgrade     { get; } = new(178, "Magic Meter (Upgrade)");
        public static Items TingleStatue50        { get; } = new(179, "50-Rupee Tingle Statue Reward");
        public static Items TingleStatue100       { get; } = new(180, "100-Rupee Tingle Statue Reward");
        public static Items TingleStatue150       { get; } = new(181, "150-Rupee Tingle Statue Reward");
        public static Items TingleStatue200       { get; } = new(182, "200-Rupee Tingle Statue Reward");
        public static Items TingleStatue250       { get; } = new(183, "250-Rupee Tingle Statue Reward");
        public static Items TingleStatue500       { get; } = new(184, "500-Rupee Tingle Statue Reward");
        public static Items Empty185              { get; } = new(185, "[Slot 185]");
        public static Items Empty186              { get; } = new(186, "[Slot 186]");
        public static Items Empty187              { get; } = new(187, "[Slot 187]");
        public static Items Empty188              { get; } = new(188, "[Slot 188]");
        public static Items Empty189              { get; } = new(189, "[Slot 189]");
        public static Items Empty190              { get; } = new(190, "[Slot 190]");
        public static Items Empty191              { get; } = new(191, "[Slot 191]");
        public static Items Empty192              { get; } = new(192, "[Slot 192]");
        public static Items Empty193              { get; } = new(193, "[Slot 193]");
        public static Items SubmarineChart        { get; } = new(194, "Submarine Chart");
        public static Items BeedlesChart          { get; } = new(195, "Beedle's Chart");
        public static Items PlatformChart         { get; } = new(196, "Platform Chart");
        public static Items LightRingChart        { get; } = new(197, "Light Ring Chart");
        public static Items SecretCaveChart       { get; } = new(198, "Secret Cave Chart");
        public static Items SeaHeartsChart        { get; } = new(199, "Sea Hearts Chart");
        public static Items IslandHeartsChart     { get; } = new(200, "Island Hearts Chart");
        public static Items GreatFairyChart       { get; } = new(201, "Great Fairy Chart");
        public static Items OctoChart             { get; } = new(202, "Octo Chart");
        public static Items INcredibleChart       { get; } = new(203, "IN-credible Chart");
        public static Items TreasureChart7        { get; } = new(204, "Treasure Chart 7");
        public static Items TreasureChart27       { get; } = new(205, "Treasure Chart 27");
        public static Items TreasureChart21       { get; } = new(206, "Treasure Chart 21");
        public static Items TreasureChart13       { get; } = new(207, "Treasure Chart 13");
        public static Items TreasureChart32       { get; } = new(208, "Treasure Chart 32");
        public static Items TreasureChart19       { get; } = new(209, "Treasure Chart 19");
        public static Items TreasureChart41       { get; } = new(210, "Treasure Chart 41");
        public static Items TreasureChart26       { get; } = new(211, "Treasure Chart 26");
        public static Items TreasureChart8        { get; } = new(212, "Treasure Chart 8");
        public static Items TreasureChart37       { get; } = new(213, "Treasure Chart 37");
        public static Items TreasureChart25       { get; } = new(214, "Treasure Chart 25");
        public static Items TreasureChart17       { get; } = new(215, "Treasure Chart 17");
        public static Items TreasureChart36       { get; } = new(216, "Treasure Chart 36");
        public static Items TreasureChart22       { get; } = new(217, "Treasure Chart 22");
        public static Items TreasureChart9        { get; } = new(218, "Treasure Chart 9");
        public static Items GhostShipChart        { get; } = new(219, "Ghost Ship Chart");
        public static Items TinglesChart          { get; } = new(220, "Tingle's Chart");
        public static Items TreasureChart14       { get; } = new(221, "Treasure Chart 14");
        public static Items TreasureChart10       { get; } = new(222, "Treasure Chart 10");
        public static Items TreasureChart40       { get; } = new(223, "Treasure Chart 40");
        public static Items TreasureChart3        { get; } = new(224, "Treasure Chart 3");
        public static Items TreasureChart4        { get; } = new(225, "Treasure Chart 4");
        public static Items TreasureChart28       { get; } = new(226, "Treasure Chart 28");
        public static Items TreasureChart16       { get; } = new(227, "Treasure Chart 16");
        public static Items TreasureChart18       { get; } = new(228, "Treasure Chart 18");
        public static Items TreasureChart34       { get; } = new(229, "Treasure Chart 34");
        public static Items TreasureChart29       { get; } = new(230, "Treasure Chart 29");
        public static Items TreasureChart1        { get; } = new(231, "Treasure Chart 1");
        public static Items TreasureChart35       { get; } = new(232, "Treasure Chart 35");
        public static Items TreasureChart12       { get; } = new(233, "Treasure Chart 12");
        public static Items TreasureChart6        { get; } = new(234, "Treasure Chart 6");
        public static Items TreasureChart24       { get; } = new(235, "Treasure Chart 24");
        public static Items TreasureChart39       { get; } = new(236, "Treasure Chart 39");
        public static Items TreasureChart38       { get; } = new(237, "Treasure Chart 38");
        public static Items TreasureChart2        { get; } = new(238, "Treasure Chart 2");
        public static Items TreasureChart33       { get; } = new(239, "Treasure Chart 33");
        public static Items TreasureChart31       { get; } = new(240, "Treasure Chart 31");
        public static Items TreasureChart23       { get; } = new(241, "Treasure Chart 23");
        public static Items TreasureChart5        { get; } = new(242, "Treasure Chart 5");
        public static Items TreasureChart20       { get; } = new(243, "Treasure Chart 20");
        public static Items TreasureChart30       { get; } = new(244, "Treasure Chart 30");
        public static Items TreasureChart15       { get; } = new(245, "Treasure Chart 15");
        public static Items TreasureChart11       { get; } = new(246, "Treasure Chart 11");
        public static Items TriforceChart8        { get; } = new(247, "Triforce Chart 8");
        public static Items TriforceChart7        { get; } = new(248, "Triforce Chart 7");
        public static Items TriforceChart6        { get; } = new(249, "Triforce Chart 6");
        public static Items TriforceChart5        { get; } = new(250, "Triforce Chart 5");
        public static Items TriforceChart4        { get; } = new(251, "Triforce Chart 4");
        public static Items TriforceChart3        { get; } = new(252, "Triforce Chart 3");
        public static Items TriforceChart2        { get; } = new(253, "Triforce Chart 2");
        public static Items TriforceChart1        { get; } = new(254, "Triforce Chart 1");
        public static Items None                  { get; } = new(255, "Nothing");

        public static Array GetValues()
        {
            List<string> names = new List<string>();

            foreach (PropertyInfo p in typeof(Items).GetProperties(BindingFlags.Public | BindingFlags.Static))
            {
                if (p.GetValue(p) is Items itm)
                {
                    names.Add(itm.Name);
                }
            }

            return names.ToArray();
        }

        public override string ToString() => Name;
    }
}
